In [14]:
import pandas as pd

df1 = pd.read_csv("./resources/movies.csv", nrows=30)
# 获取索引      RangeIndex(start=0, stop=30, step=1)
# df1.index

# 获取值
# df1.values

# 获取各列的数据类型
# df1.dtypes

# 获取数据个数    330
# df1.size

# 获取维度      (30, 11)
# df1.shape

# 获取列名
# df1.columns

Index(['电影名', '年份', '上映时间', '类型', '时长', '评分', '语言', '导演', '作者', '宣传语', '简介'], dtype='object')

In [24]:
import pandas as pd
# nrows 限制输出行数    usecols 只读取指定列
df2 = pd.read_csv("./resources/movies.csv", nrows=30, usecols=['电影名', '上映时间', '类型', '评分', '语言'])
# df2

# 获取到 电影名 和 评分 将其写入 movies_output.csv文件中
# output = df2[['电影名','评分']].to_csv("./resources/movies_output.csv", index=False)

In [36]:
# 数据的查看
import pandas as pd

df3 = pd.read_csv("./resources/movies.csv", nrows=30)

# head() 默认输出前5行内容
# df3.head()
# 输出前8行内容
# df3.head(8)

# tail() 默认输出最后5行内容
# df3.tail()
# df3.tail(11)

# 数值列的统计描述（计数、均值、标准差、最大最小值等）
# df3.describe()

# 查看数据信息（列名、非空计数、数据类型）
# df3.info()

# 查看数据维度（行数，列数）     (30,11)
# df3.shape

# 查看列名
# df3.columns

In [42]:
# 数据的选择
import pandas as pd

df4 = pd.read_csv("./resources/movies.csv", nrows=30)

# 单列返回
# df4['电影名']

# 多列返回
# df4[['电影名', '评分']]

# 行
# iloc[start:stop:step] 基于行号选择 不含stop  
# df4.iloc[0:4]

# loc[start:stop:step] 基索引号选择 含stop  索引可以自己设定(index_col=)
# df4.loc[0:4]

In [51]:
# 数据过滤
import pandas as pd

df5 = pd.read_csv("./resources/movies.csv", nrows=30)

# 评分大于86分的电影信息
# df5[df5["评分"] >= 86]

# 评分在 85~87之间的电影信息
# df5[df5["评分"].between(85,87)]

# 语言在日语和法语的电影信息
# df5[df5['语言'].isin(['日语', '法语'])]

# 语言在日语和法语的电影信息并且评分高于84分
df5[(df5['语言'].isin(['日语', '法语'])) & (df5['评分'] > 84)]

,电影名,年份,上映时间,类型,时长,评分,语言,导演,作者,宣传语,简介
7,千与千寻,2001.0,2019-06-21,"动画,家庭,奇幻",125,85,日语,宫崎骏,NaN,隧道的另一头，是不可思议的小镇,小女孩千寻被困在一个陌生的精灵世界。当她的父母发生神秘变化后，她必须鼓起自己从未发现的勇气，...
14,你的名字。,2016.0,2016-12-02,"动画,爱情,剧情",106,85,日语,新海诚,NaN,我正在寻觅未曾相识的你。,在远离大都会的小山村，住着巫女世家出身的高中女孩宫水三叶（上白石萌音 配音）。校园和家庭的原...
18,人类,2015.0,2015-09-12,纪录,191,85,法语,Yann Arthus-Bertrand,NaN,简介,每个人背后都有一个足以撼动心灵的故事。法国知名的摄影师Yann Arthus-Bertran...
20,七武士,1954.0,1954-04-26,"动作,剧情",207,85,日语,黑泽明,桥本忍,在悬念和场面方面无与伦比！,这部影史最具震撼力的史诗巨制，讲述十六世纪某村庄的绝望村民雇佣七位武士抵御山贼侵袭的故事。黑...

In [52]:
# 数据清洗
import pandas as pd

df6 = pd.read_csv("./resources/movies.csv", nrows=30)

# 判断每个单元格是否为空(返回值为布尔类型)
df6.isnull()

,电影名,年份,上映时间,类型,时长,评分,语言,导演,作者,宣传语,简介
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,True,False,False
7,False,False,False,False,False,False,False,False,True,False,False
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,True,False,False
10,False,False,False,False,False,False,False,False,False,False,False
11,False,True,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,True,False,False
15,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,True,False,False
19,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,True,False,False
23,False,False,False,False,False,False,False,False,False,False,False
24,False,True,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False